checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: checkpoints
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false

data_stages:
  - name: Stable Training Stage
    start_training_step: 1
    data:
      dataset:
        dataset_overwrite_cache: false
        dataset_processing_num_proc_per_process: 1
        hf_dataset_config_name: null
        hf_dataset_or_datasets: Fiery101/radar_textbooks
        hf_dataset_splits: train
        text_column_name: text
      num_loading_workers: 1
      seed: 42

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: false
  project: ÂµTransfer_for_nanotron
  run: llama_width_128_config
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 120
  dtype: bfloat16
  init_method:
    std: 0.08838834764831843 # 1/sqrt(128)=0.08838834764831843
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    initializer_range: 0.02

    # NOTE: 250m
    # hidden_size: 1024
    # intermediate_size: 4096
    # num_hidden_layers: 10

    hidden_size: 128
    intermediate_size: 512
    num_hidden_layers: 4

    is_llama_config: true
    max_position_embeddings: 1024
    num_attention_heads: 32
    num_key_value_heads: 4
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    # tie_word_embeddings: true
    tie_word_embeddings: false # original use true
    use_cache: true
    vocab_size: 49152
optimizer:
  accumulate_grad_in_fp32: false
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.001 # note: 1/2 of pythia use this for a 400m model
    lr_decay_starting_step: null
    lr_decay_steps: null
    lr_decay_style: cosine
    lr_warmup_steps: 6 # 10% warm up of total training steps
    lr_warmup_style: linear
    min_decay_lr: 1.0e-05
  torch_adam_is_fused: true
  weight_decay: 0.1
  zero_stage: 1
parallelism:
  dp: 2
  pp: 1
  pp_engine: 1f1b
  tp: 4
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: lvwerra/the-tokenizer-v1
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 64
  sequence_length: 512
  train_steps: 30
  val_check_interval: -1
