checkpoints:
  checkpoint_interval: 5000
  checkpoints_path: checkpoints
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false

# data_stages:
#   - name: Stable Training Stage
#     start_training_step: 1
#     data:
#       dataset:
#         dataset_overwrite_cache: false
#         dataset_processing_num_proc_per_process: 1
#         # hf_dataset_config_name: null
#         # hf_dataset_or_datasets: Fiery101/radar_textbooks
#         # hf_dataset_splits: train
#         # text_column_name: text

#         # hf_dataset_config_name: wikitext-103-raw-v1
#         # hf_dataset_or_datasets: wikitext
#         # hf_dataset_splits: train
#         # text_column_name: text

#         # hf_dataset_config_name: null
#         # hf_dataset_or_datasets: Skylion007/openwebtext
#         # hf_dataset_splits: train
#         # text_column_name: text

#       num_loading_workers: 1
#       seed: 42


data:
  dataset:
    dataloader_type: single
    dataset_max_tokens: null
    dataset_weights:
    - 0.0625 # fineweb
    - 0.0625 # stack_full
    - 0.0625 # c4
    - 0.0625 # arxiv
    - 0.0625 # synthetic-data
    - 0.0625 # stack-pull-requests
    - 0.0625 # stack-jupyter-scripts
    - 0.0625 # stack-jupyter-structured
    - 0.0625 # open-web-math
    - 0.0625 # stack-issues
    - 0.0625 # stackoverflow
    - 0.0625 # wikipedia
    - 0.0625 # project-gutenberg
    - 0.0625 # deepmind-math
    - 0.0625 # stack-kaggle-scripts
    - 0.0625 # stack-documentation
    datasets:
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/fineweb/000_CC-MAIN-2023-50.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/stack_full/000_stack_full.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/c4/000_c4.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/arxiv/000_arxiv.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/synthetic-data/000_synthetic-data.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/stack-pull-requests/000_stack-pull-requests.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/stack-jupyter-scripts/000_stack-jupyter-scripts.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/stack-jupyter-structured/000_stack-jupyter-structured.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/open-web-math/000_open-web-math.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/stack-issues/000_stack_issues.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/stackoverflow/000_stackoverflow.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/wikipedia/000_wikipedia.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/project-gutenberg/000_project_gutenberg.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/deepmind-math/000_deepmind-math.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/stack-kaggle-scripts/000_stack-kaggle-scripts.ds
      skip_tokens: 0
    - filepath: /fsx/phuc/datasets/huggingface-llm-datasets/first_shard/stack-documentation/000_stack-documentation.ds
      skip_tokens: 0

    pad_samples_to_global_batch_size: false
    skip_in_stream: true
  num_loading_workers: 0
  seed: 1234

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: false
  project: µTransfer_for_nanotron
  run: exp7_mu_llama_width_8192_config
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 120
  dtype: bfloat16
  init_method:
    # std: 0.025 # original
    # std: 0.03125 # 1/sqrt(1024)=0.03125
    std: 0.011048543456039804 # 1/sqrt(8192)=0.011048543456039804
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    initializer_range: 0.02

    hidden_size: 8192
    intermediate_size: 32768

    num_hidden_layers: 4

    is_llama_config: true
    max_position_embeddings: 1024
    num_attention_heads: 32
    num_key_value_heads: 4
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    # tie_word_embeddings: true
    tie_word_embeddings: false # original use true
    use_cache: true
    vocab_size: 49152
optimizer:
  accumulate_grad_in_fp32: false
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.001 # note: 1/2 of pythia use this for a 400m model
    lr_decay_starting_step: null
    lr_decay_steps: null
    lr_decay_style: cosine
    lr_warmup_steps: 2000 # 10% warm up of total training steps
    lr_warmup_style: linear
    min_decay_lr: 1.0e-05
  torch_adam_is_fused: true
  weight_decay: 0.1
  zero_stage: 1
parallelism:
  dp: 16
  pp: 1
  tp: 2
  pp_engine: 1f1b

  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: lvwerra/the-tokenizer-v1
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 32
  sequence_length: 1024
  train_steps: 10_000
  val_check_interval: -1


experiment_logger:
  tensorboard_logger:
    flush_secs: 30
    tensorboard_dir: /fsx/phuc/project_data/µTransfer_for_nanotron/tb_logs
  wandb_logger:
    wandb_entity: null
    wandb_project: µTransfer_for_nanotron
