checkpoints:
  checkpoint_interval: 10
  checkpoints_path: checkpoints
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: false
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_folder:
      - /fsx/loubna/tokenized_for_exps/mcf-dataset
      dataset_weights: null
      token_size_in_bytes: 2
      tokenizer_name: HuggingFaceTB/cosmo2-tokenizer
      vocab_size: 49152
    num_loading_workers: 1
    seed: 42
  name: Stable Training Stage
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: false
  project: debug
  run: qwen_20250326_140547_15645583
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flex_attention
    attention_bias: false
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 256
    initializer_range: 0.02
    interleaved_rotary: false
    intermediate_size: 768
    is_qwen2_config: true
    max_position_embeddings: 256
    moe_config: null
    num_attention_heads: 4
    num_hidden_layers: 12
    num_key_value_heads: 4
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    rope_theta: 10000.0
    sliding_window_size: 20
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 49152
    z_loss_coefficient: 0.0001
    z_loss_enabled: false
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_starting_step: null
    lr_decay_steps: 13
    lr_decay_style: cosine
    lr_warmup_steps: 2
    lr_warmup_style: linear
    min_decay_lr: 1.0e-05
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  weight_decay_exclude_named_params: []
  zero_stage: 0
parallelism:
  context_parallel_size: 1
  dp: 1
  expert_parallel_size: 1
  moe_layer_recompute: false
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 2
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
s3_upload: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: HuggingFaceTB/cosmo2-tokenizer
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 3
  sequence_length: 8192
  train_steps: 15
  val_check_interval: -1
